### ISSUE TITLE
MissingFieldException: 'known_for_department'

### ISSUE THREAD

**Issue by edmundjohnson** [MoviebaseApp/tmdb-api#9] opened 2021-12-29 13:14 UTC
I'm getting an exception with v0.6.3 when calling
`Tmdb3.find.find("tt11271038", "en", TmdbExternalSource.IMDB) `

Stacktrace:

```
    kotlinx.serialization.MissingFieldException: 
     Field 'known_for_department' is required for type with serial name 'app.moviebase.tmdb.model.TmdbCrew', but it was missing
        at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
        at app.moviebase.tmdb.model.TmdbCrew.<init>(TmdbPeopleModel.kt:115)
        at app.moviebase.tmdb.model.TmdbCrew$$serializer.deserialize(TmdbPeopleModel.kt:115)
        at app.moviebase.tmdb.model.TmdbCrew$$serializer.deserialize(TmdbPeopleModel.kt:115)

```

**Comment by chrisnkrueger** [comment] 2022-01-07 08:12
Thanks. I will check this field.

**Comment by chrisnkrueger** [comment] 2022-01-08 10:53
The issue is fixed in version 0.6.4

**Closed by chrisnkrueger** 2022-01-08 10:53 UTC
Labels: bug

**Comment by edmundjohnson** [comment] 2022-01-09 17:32
Thank you!
